apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: onetime-base
  namespace: onetime

resources:
- namespace.yaml
- secrets.yaml
- api-gateway-deployment.yaml
- user-service-deployment.yaml
- database-deployment.yaml
- elasticsearch-deployment.yaml
- monitoring.yaml

commonLabels:
  app.kubernetes.io/name: onetime
  app.kubernetes.io/part-of: onetime-platform

images:
- name: onetime/api-gateway
  newTag: latest
- name: onetime/user-service  
  newTag: latest

configMapGenerator:
- name: onetime-config
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=info
  - API_VERSION=v1

secretGenerator:
- name: onetime-secrets-gen
  literals:
  - jwt-secret=your-super-secret-jwt-key-change-this-in-production
  type: Opaque