apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: onetime
  labels:
    app: user-service
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        component: backend
    spec:
      initContainers:
      - name: migrate
        image: onetime/user-service:latest
        command: ['npx', 'prisma', 'migrate', 'deploy']
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: onetime-secrets
              key: user-database-url
      containers:
      - name: user-service
        image: onetime/user-service:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: onetime-secrets
              key: user-database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: onetime-secrets
              key: jwt-secret
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: onetime-secrets
              key: smtp-user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: onetime-secrets
              key: smtp-pass
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: logs
        emptyDir: {}
      - name: uploads
        persistentVolumeClaim:
          claimName: user-service-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: onetime
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-uploads-pvc
  namespace: onetime
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client